package com.example.yb.hstt.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.yb.hstt.dao.bean.DeviceInfos;
import com.example.yb.hstt.dao.bean.LoginInfo;
import com.example.yb.hstt.dao.bean.TaskInfo;
import com.example.yb.hstt.dao.bean.UserInfo;

import com.example.yb.hstt.dao.DeviceInfosDao;
import com.example.yb.hstt.dao.LoginInfoDao;
import com.example.yb.hstt.dao.TaskInfoDao;
import com.example.yb.hstt.dao.UserInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig deviceInfosDaoConfig;
    private final DaoConfig loginInfoDaoConfig;
    private final DaoConfig taskInfoDaoConfig;
    private final DaoConfig userInfoDaoConfig;

    private final DeviceInfosDao deviceInfosDao;
    private final LoginInfoDao loginInfoDao;
    private final TaskInfoDao taskInfoDao;
    private final UserInfoDao userInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        deviceInfosDaoConfig = daoConfigMap.get(DeviceInfosDao.class).clone();
        deviceInfosDaoConfig.initIdentityScope(type);

        loginInfoDaoConfig = daoConfigMap.get(LoginInfoDao.class).clone();
        loginInfoDaoConfig.initIdentityScope(type);

        taskInfoDaoConfig = daoConfigMap.get(TaskInfoDao.class).clone();
        taskInfoDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        deviceInfosDao = new DeviceInfosDao(deviceInfosDaoConfig, this);
        loginInfoDao = new LoginInfoDao(loginInfoDaoConfig, this);
        taskInfoDao = new TaskInfoDao(taskInfoDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);

        registerDao(DeviceInfos.class, deviceInfosDao);
        registerDao(LoginInfo.class, loginInfoDao);
        registerDao(TaskInfo.class, taskInfoDao);
        registerDao(UserInfo.class, userInfoDao);
    }
    
    public void clear() {
        deviceInfosDaoConfig.clearIdentityScope();
        loginInfoDaoConfig.clearIdentityScope();
        taskInfoDaoConfig.clearIdentityScope();
        userInfoDaoConfig.clearIdentityScope();
    }

    public DeviceInfosDao getDeviceInfosDao() {
        return deviceInfosDao;
    }

    public LoginInfoDao getLoginInfoDao() {
        return loginInfoDao;
    }

    public TaskInfoDao getTaskInfoDao() {
        return taskInfoDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

}
